name: Linting and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=PSR12 ./lib/

      - name: Run PHPMD
        run: ./vendor/bin/phpmd ./lib ansi codesize,unusedcode,naming

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse ./lib --level=max
